services:
  db:
    image: docker.io/library/postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}       
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - internal

  web:
    build: .
    container_name: herbariet_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app/herbariet/
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_LOCAL_NAME=${DB_NAME}
      - DB_LOCAL_USER=${DB_USER}
      - DB_LOCAL_PASS=${DB_PASSWORD}
      - DJANGO_SETTINGS_MODULE=herbariet.settings.dev

    networks:
      - internal

volumes:
  pgdata:

networks:
  internal:
    driver: bridge